# Netlify configuration for SPA client-side routing
# This ensures that all page requests are sent to index.html, allowing
# the Vue router to handle routing client-side and prevent 404 errors
# when refreshing the page on routes other than the root.

[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
